In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from joblib import dump, load

# Get data

In [2]:
df_train = pd.read_csv('twitter_training.csv',header=None)
df_train.columns = ['#', 'refers to', 'sentiment', 'text']
df_train.head()

,#,refers to,sentiment,text
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [3]:
df_test = pd.read_csv('twitter_validation.csv',header=None)
df_test.columns = ['#', 'refers to', 'sentiment', 'text']
df_test.head()

,#,refers to,sentiment,text
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...

# Feature engineering

In [4]:
[df_test.shape, df_train.shape]

[(1000, 4), (74682, 4)]

In [5]:
print(df_test.isnull().sum(),'\n\n',df_train.isnull().sum())

#            0
refers to    0
sentiment    0
text         0
dtype: int64

 #              0
refers to      0
sentiment      0
text         686
dtype: int64

In [6]:
df_train.dropna(inplace=True, axis=0)

In [7]:
ids_to_remove = [1826, 10454, 32186, 68078]
df_train = df_train[~df_train.index.isin(ids_to_remove)]
df_train.index = range(len(df_train))

In [8]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

X_train = df_train['text']
y_train = le.fit_transform(df_train['sentiment'])

X_test = df_test['text']
y_test = le.transform(df_test['sentiment'])

In [9]:
print(np.unique(y_test))
print(le.inverse_transform(np.unique(y_test)))

[0 1 2 3]
['Irrelevant' 'Negative' 'Neutral' 'Positive']

In [10]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = set(stopwords.words('english'))
len(stopwords)

198

In [11]:
dump(stopwords, 'stopwords.data')

['stopwords.data']

In [12]:
import spacy
nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
import regex as re

In [13]:
dump(nlp, 'nlp.path') 
dump(stopwords, 'stopwords.data')

['stopwords.data']

In [14]:
class Preprocessor:
    def __init__(self, stopwords=stopwords):
        self.vectorizer = TfidfVectorizer(lowercase=False, max_features=8000,
                                         min_df=10, ngram_range=(1, 3),
                                         tokenizer=None)
        self.stopwords = stopwords
        self.vectorizer_fitted = False
        
    def remove_urls(self, texts):
        print('Removing URLs...')
        pattern = re.compile(r'(\w+\.com ?/ ?.+)|(http\S+)')
        return [re.sub(pattern, '', text) for text in texts]
    
    def remove_double_space(self, texts):
        print('Removing double space...')
        pattern = re.compile(' +')
        return [re.sub(pattern, ' ', text) for text in texts]
        
    def remove_punctuation(self, texts):
        print('Removing Punctuation...')
        pattern = re.compile('[^a-z ]')
        return [re.sub(pattern, ' ', text) for text in texts]
    
    def remove_stopwords(self, texts):
        print('Removing stopwords...')
        return [[w for w in text.split(' ') if w not in self.stopwords] for text in tqdm(texts)]
    
    def remove_numbers(self, texts):
        print('Removing numbers...')
        return [' '.join([w for w in text if not w.isdigit()]) for text in tqdm(texts)]
    
    def remove_emojis(self, texts):
        print('Removing emojis...')
        pattern = re.compile("["
                u"\U0001F600-\U0001F64F"  # emoticons
                u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                u"\U0001F680-\U0001F6FF"  # transport & map symbols
                u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                                   "]+", flags=re.UNICODE)
        return [re.sub(pattern, r'', text) for text in texts]
    
    def lemmatize(self, texts):
        print('Lemmatizing...')
        lemmatized_texts = []
        for doc in tqdm(nlp.pipe(texts, batch_size=1000), total=len(texts)):
            lemmatized_texts.append(' '.join([token.lemma_ for token in doc]))
                                    
        return lemmatized_texts
        
    def transform(self, X, y=None, mode='train'):
        X = X.copy()
        
        print('Removing Nans...')
        X = X[~X.isnull()]                          
        X = X[~X.duplicated()]                      
        
        if mode == 'train':
            self.train_idx = X.index
        else:
            self.test_idx = X.index
            
        print('Counting capitalized...')
        capitalized = [np.sum([t.isupper() for t in text.split()]) 
                           for text in np.array(X.values)]  
        
        print('Lowering...')
        X = [text.lower() for text in X]   
        
        X = self.remove_urls(X)                      
        X = self.remove_punctuation(X)               
        X = self.remove_double_space(X)             
        X = self.remove_emojis(X)                   
        X = self.remove_stopwords(X)                 
        X = self.remove_numbers(X)                                        
        X = self.lemmatize(X)                        
        
        if not self.vectorizer_fitted:
            self.vectorizer_fitted = True
            print('Fitting vectorizer...')
            self.vectorizer.fit(X)

        print('Vectorizing...')
        X = self.vectorizer.transform(X)       
        
        return X

In [15]:
pr = Preprocessor()

In [16]:
data_train = pr.transform(X_train)
data_train = pd.DataFrame.sparse.from_spmatrix(data_train, columns=pr.vectorizer.get_feature_names_out())
y_train = pd.DataFrame(y_train)
y_train = y_train[y_train.index.isin(pr.train_idx)]
y_train.index = data_train.index

Removing Nans...
Counting capitalized...

Lowering...
Removing URLs...

Removing Punctuation...

Removing double space...

Removing emojis...

Removing stopwords...

  0%|          | 0/69488 [00:00<?, ?it/s]

 43%|████▎     | 30021/69488 [00:00<00:00, 300167.35it/s]

 86%|████████▋ | 60038/69488 [00:00<00:00, 284641.91it/s]

100%|██████████| 69488/69488 [00:00<00:00, 142073.69it/s]

Removing numbers...

  0%|          | 0/69488 [00:00<?, ?it/s]

100%|██████████| 69488/69488 [00:00<00:00, 929040.04it/s]

Lemmatizing...

  0%|          | 0/69488 [00:00<?, ?it/s]

  0%|          | 1/69488 [00:00<11:53:02,  1.62it/s]

  0%|          | 205/69488 [00:00<03:00, 384.83it/s]

  1%|          | 378/69488 [00:00<01:43, 669.41it/s]

  1%|          | 599/69488 [00:00<01:07, 1026.03it/s]

  1%|          | 817/69488 [00:01<00:52, 1311.76it/s]

  1%|▏         | 1007/69488 [00:01<01:55, 595.04it/s]

  2%|▏         | 1278/69488 [00:01<01:18, 873.31it/s]

  2%|▏         | 1484/69488 [00:01<01:04, 1061.12it/s]

  2%|▏         | 1732/69488 [00:01<00:51, 1320.70it/s]

  3%|▎         | 1967/69488 [00:02<00:44, 1534.33it/s]

  3%|▎         | 2182/69488 [00:02<01:24, 794.50it/s]

  4%|▎         | 2518/69488 [00:02<00:58, 1136.80it/s]

  4%|▍         | 2936/69488 [00:02<00:40, 1626.07it/s]

  5%|▍         | 3211/69488 [00:03<01:03, 1042.67it/s]

  5%|▌         | 3523/69488 [00:03<00:50, 1315.26it/s]

  6%|▌         | 3909/69488 [00:03<00:38, 1716.90it/s]

  6%|▌         | 4192/69488 [00:04<01:08, 950.54it/s]

  6%|▋         | 4476/69488 [00:04<00:55, 1165.99it/s]

  7%|▋         | 4708/69488 [00:04<00:49, 1318.12it/s]

  7%|▋         | 4936/69488 [00:04<00:44, 1454.46it/s]

  7%|▋         | 5158/69488 [00:05<01:29, 718.10it/s]

  8%|▊         | 5438/69488 [00:05<01:07, 943.62it/s]

  8%|▊         | 5637/69488 [00:05<00:59, 1065.18it/s]

  8%|▊         | 5871/69488 [00:05<00:50, 1267.08it/s]

  9%|▊         | 6076/69488 [00:06<01:26, 732.59it/s]

  9%|▉         | 6261/69488 [00:06<01:12, 867.00it/s]

  9%|▉         | 6525/69488 [00:06<00:55, 1125.58it/s]

 10%|▉         | 6873/69488 [00:06<00:40, 1532.55it/s]

 10%|█         | 7112/69488 [00:07<01:05, 946.45it/s]

 11%|█         | 7474/69488 [00:07<00:47, 1308.35it/s]

 11%|█▏        | 7839/69488 [00:07<00:36, 1688.61it/s]

 12%|█▏        | 8113/69488 [00:07<00:59, 1032.58it/s]

 12%|█▏        | 8400/69488 [00:07<00:48, 1267.35it/s]

 12%|█▏        | 8631/69488 [00:07<00:45, 1341.32it/s]

 13%|█▎        | 9001/69488 [00:08<01:02, 974.28it/s]

 13%|█▎        | 9310/69488 [00:08<00:48, 1229.20it/s]

 14%|█▍        | 9601/69488 [00:08<00:40, 1475.94it/s]

 14%|█▍        | 9923/69488 [00:08<00:33, 1777.73it/s]

 15%|█▍        | 10184/69488 [00:09<00:57, 1035.81it/s]

 15%|█▌        | 10577/69488 [00:09<00:41, 1415.78it/s]

 16%|█▌        | 10954/69488 [00:09<00:32, 1785.26it/s]

 16%|█▌        | 11245/69488 [00:10<00:54, 1078.25it/s]

 17%|█▋        | 11537/69488 [00:10<00:44, 1307.52it/s]

 17%|█▋        | 11890/69488 [00:10<00:35, 1642.95it/s]

 18%|█▊        | 12165/69488 [00:11<01:02, 919.25it/s]

 18%|█▊        | 12488/69488 [00:11<00:48, 1178.67it/s]

 18%|█▊        | 12777/69488 [00:11<00:40, 1414.01it/s]

 19%|█▉        | 13031/69488 [00:11<01:02, 907.30it/s]

 19%|█▉        | 13420/69488 [00:11<00:44, 1258.06it/s]

 20%|█▉        | 13868/69488 [00:11<00:32, 1721.41it/s]

 20%|██        | 14178/69488 [00:12<00:47, 1153.40it/s]

 21%|██        | 14530/69488 [00:12<00:37, 1449.83it/s]

 22%|██▏       | 14977/69488 [00:12<00:28, 1905.16it/s]

 22%|██▏       | 15298/69488 [00:13<00:41, 1304.23it/s]

 23%|██▎       | 15760/69488 [00:13<00:30, 1749.92it/s]

 23%|██▎       | 16071/69488 [00:13<00:43, 1235.23it/s]

 24%|██▍       | 16576/69488 [00:13<00:30, 1716.13it/s]

 24%|██▍       | 17001/69488 [00:14<00:44, 1190.24it/s]

 25%|██▍       | 17245/69488 [00:14<00:39, 1317.71it/s]

 25%|██▌       | 17627/69488 [00:14<00:31, 1654.91it/s]

 26%|██▌       | 17966/69488 [00:14<00:26, 1934.84it/s]

 26%|██▋       | 18265/69488 [00:15<00:48, 1063.63it/s]

 27%|██▋       | 18598/69488 [00:15<00:38, 1330.52it/s]

 27%|██▋       | 18885/69488 [00:15<00:32, 1551.88it/s]

 28%|██▊       | 19151/69488 [00:16<00:52, 957.93it/s]

 28%|██▊       | 19450/69488 [00:16<00:41, 1198.11it/s]

 28%|██▊       | 19757/69488 [00:16<00:33, 1468.57it/s]

 29%|██▉       | 20010/69488 [00:17<00:58, 841.09it/s]

 29%|██▉       | 20354/69488 [00:17<00:43, 1128.91it/s]

 30%|██▉       | 20698/69488 [00:17<00:33, 1443.82it/s]

 30%|███       | 20966/69488 [00:17<00:31, 1537.25it/s]

 31%|███       | 21210/69488 [00:18<01:03, 761.10it/s]

 31%|███       | 21564/69488 [00:18<00:45, 1046.29it/s]

 31%|███▏      | 21870/69488 [00:18<00:36, 1303.90it/s]

 32%|███▏      | 22124/69488 [00:19<01:00, 783.84it/s]

 32%|███▏      | 22363/69488 [00:19<00:49, 950.21it/s]

 33%|███▎      | 22635/69488 [00:19<00:39, 1178.53it/s]

 33%|███▎      | 22876/69488 [00:19<00:34, 1369.97it/s]

 33%|███▎      | 23106/69488 [00:20<01:04, 720.14it/s]

 34%|███▎      | 23429/69488 [00:20<00:46, 991.76it/s]

 34%|███▍      | 23645/69488 [00:20<00:40, 1131.10it/s]

 34%|███▍      | 23906/69488 [00:20<00:33, 1365.15it/s]

 35%|███▍      | 24131/69488 [00:20<00:56, 797.13it/s]

 35%|███▌      | 24512/69488 [00:21<00:38, 1161.02it/s]

 36%|███▌      | 24804/69488 [00:21<00:31, 1420.03it/s]

 36%|███▌      | 25054/69488 [00:21<00:49, 905.60it/s]

 37%|███▋      | 25443/69488 [00:21<00:34, 1271.50it/s]

 37%|███▋      | 25816/69488 [00:21<00:26, 1637.73it/s]

 38%|███▊      | 26102/69488 [00:22<00:39, 1104.40it/s]

 38%|███▊      | 26530/69488 [00:22<00:28, 1515.99it/s]

 39%|███▊      | 26904/69488 [00:22<00:22, 1864.22it/s]

 39%|███▉      | 27213/69488 [00:23<00:33, 1249.98it/s]

 40%|███▉      | 27551/69488 [00:23<00:27, 1537.42it/s]

 40%|████      | 27817/69488 [00:23<00:24, 1713.67it/s]

 40%|████      | 28082/69488 [00:23<00:41, 988.10it/s]

 41%|████      | 28512/69488 [00:23<00:29, 1394.57it/s]

 41%|████▏     | 28836/69488 [00:24<00:24, 1669.34it/s]

 42%|████▏     | 29121/69488 [00:24<00:41, 973.28it/s]

 42%|████▏     | 29521/69488 [00:24<00:30, 1321.45it/s]

 43%|████▎     | 29890/69488 [00:24<00:23, 1655.84it/s]

 43%|████▎     | 30189/69488 [00:25<00:37, 1042.59it/s]

 44%|████▍     | 30567/69488 [00:25<00:28, 1363.75it/s]

 44%|████▍     | 30914/69488 [00:25<00:23, 1665.09it/s]

 45%|████▍     | 31207/69488 [00:26<00:35, 1079.81it/s]

 45%|████▌     | 31525/69488 [00:26<00:28, 1336.79it/s]

 46%|████▌     | 31946/69488 [00:26<00:21, 1764.04it/s]

 46%|████▋     | 32248/69488 [00:26<00:34, 1078.54it/s]

 47%|████▋     | 32534/69488 [00:27<00:28, 1289.05it/s]

 47%|████▋     | 32831/69488 [00:27<00:23, 1534.22it/s]

 48%|████▊     | 33090/69488 [00:27<00:44, 823.29it/s]

 48%|████▊     | 33349/69488 [00:28<00:35, 1009.78it/s]

 48%|████▊     | 33676/69488 [00:28<00:27, 1305.93it/s]

 49%|████▉     | 33983/69488 [00:28<00:22, 1583.64it/s]

 49%|████▉     | 34248/69488 [00:28<00:43, 806.68it/s]

 50%|████▉     | 34578/69488 [00:29<00:32, 1071.88it/s]

 50%|█████     | 34902/69488 [00:29<00:25, 1356.37it/s]

 51%|█████     | 35164/69488 [00:29<00:39, 876.22it/s]

 51%|█████     | 35417/69488 [00:29<00:32, 1062.81it/s]

 51%|█████▏    | 35758/69488 [00:29<00:24, 1386.34it/s]

 52%|█████▏    | 36009/69488 [00:30<00:43, 768.34it/s]

 52%|█████▏    | 36321/69488 [00:30<00:32, 1011.55it/s]

 53%|█████▎    | 36662/69488 [00:30<00:24, 1320.39it/s]

 53%|█████▎    | 36967/69488 [00:30<00:20, 1588.92it/s]

 54%|█████▎    | 37240/69488 [00:31<00:33, 950.84it/s]

 54%|█████▍    | 37652/69488 [00:31<00:23, 1333.43it/s]

 55%|█████▍    | 38001/69488 [00:32<00:32, 980.38it/s]

 55%|█████▌    | 38437/69488 [00:32<00:22, 1355.33it/s]

 56%|█████▌    | 38872/69488 [00:32<00:17, 1763.67it/s]

 56%|█████▋    | 39194/69488 [00:33<00:28, 1058.64it/s]

 57%|█████▋    | 39516/69488 [00:33<00:23, 1295.92it/s]

 57%|█████▋    | 39801/69488 [00:33<00:19, 1506.54it/s]

 58%|█████▊    | 40072/69488 [00:33<00:30, 949.50it/s]

 58%|█████▊    | 40440/69488 [00:33<00:23, 1261.60it/s]

 59%|█████▊    | 40693/69488 [00:34<00:20, 1392.60it/s]

 59%|█████▉    | 41001/69488 [00:34<00:32, 866.40it/s]

 59%|█████▉    | 41262/69488 [00:34<00:26, 1054.04it/s]

 60%|█████▉    | 41515/69488 [00:34<00:22, 1250.74it/s]

 60%|██████    | 41769/69488 [00:35<00:19, 1456.56it/s]

 60%|██████    | 42001/69488 [00:35<00:34, 798.58it/s]

 61%|██████    | 42327/69488 [00:35<00:25, 1083.98it/s]

 61%|██████▏   | 42717/69488 [00:35<00:18, 1484.01it/s]

 62%|██████▏   | 43001/69488 [00:36<00:34, 761.19it/s]

 62%|██████▏   | 43343/69488 [00:36<00:25, 1018.43it/s]

 63%|██████▎   | 43690/69488 [00:36<00:19, 1315.91it/s]

 63%|██████▎   | 44001/69488 [00:37<00:30, 843.68it/s]

 64%|██████▎   | 44275/69488 [00:37<00:24, 1035.20it/s]

 64%|██████▍   | 44601/69488 [00:37<00:18, 1315.57it/s]

 65%|██████▍   | 44898/69488 [00:37<00:15, 1567.61it/s]

 65%|██████▍   | 45166/69488 [00:38<00:26, 926.60it/s]

 65%|██████▌   | 45512/69488 [00:38<00:19, 1226.06it/s]

 66%|██████▌   | 45911/69488 [00:38<00:14, 1625.24it/s]

 66%|██████▋   | 46202/69488 [00:39<00:22, 1014.93it/s]

 67%|██████▋   | 46567/69488 [00:39<00:17, 1327.24it/s]

 68%|██████▊   | 46940/69488 [00:39<00:13, 1675.00it/s]

 68%|██████▊   | 47236/69488 [00:40<00:22, 1007.14it/s]

 69%|██████▊   | 47629/69488 [00:40<00:16, 1343.32it/s]

 69%|██████▉   | 47988/69488 [00:40<00:12, 1659.54it/s]

 69%|██████▉   | 48286/69488 [00:40<00:20, 1011.67it/s]

 70%|███████   | 48650/69488 [00:41<00:15, 1311.67it/s]

 71%|███████   | 49001/69488 [00:41<00:20, 996.09it/s]

 71%|███████   | 49395/69488 [00:41<00:15, 1318.95it/s]

 72%|███████▏  | 49814/69488 [00:41<00:11, 1706.89it/s]

 72%|███████▏  | 50123/69488 [00:42<00:17, 1100.38it/s]

 73%|███████▎  | 50507/69488 [00:42<00:13, 1419.58it/s]

 73%|███████▎  | 50844/69488 [00:42<00:10, 1697.59it/s]

 74%|███████▎  | 51140/69488 [00:43<00:18, 967.28it/s]

 74%|███████▍  | 51572/69488 [00:43<00:13, 1332.91it/s]

 75%|███████▍  | 51888/69488 [00:43<00:11, 1578.41it/s]

 75%|███████▌  | 52181/69488 [00:44<00:18, 959.62it/s]

 75%|███████▌  | 52445/69488 [00:44<00:14, 1143.81it/s]

 76%|███████▌  | 52816/69488 [00:44<00:11, 1491.04it/s]

 76%|███████▋  | 53090/69488 [00:44<00:18, 904.78it/s]

 77%|███████▋  | 53518/69488 [00:45<00:12, 1276.10it/s]

 78%|███████▊  | 53892/69488 [00:45<00:09, 1610.38it/s]

 78%|███████▊  | 54194/69488 [00:45<00:15, 993.85it/s]

 78%|███████▊  | 54457/69488 [00:45<00:12, 1175.89it/s]

 79%|███████▉  | 54784/69488 [00:45<00:10, 1461.50it/s]

 79%|███████▉  | 55047/69488 [00:46<00:15, 924.94it/s]

 80%|███████▉  | 55378/69488 [00:46<00:11, 1200.74it/s]

 80%|████████  | 55716/69488 [00:46<00:09, 1509.06it/s]

 81%|████████  | 56001/69488 [00:47<00:13, 965.27it/s]

 81%|████████  | 56303/69488 [00:47<00:10, 1207.66it/s]

 82%|████████▏ | 56636/69488 [00:47<00:08, 1513.46it/s]

 82%|████████▏ | 56979/69488 [00:47<00:06, 1840.80it/s]

 82%|████████▏ | 57266/69488 [00:48<00:11, 1083.81it/s]

 83%|████████▎ | 57688/69488 [00:48<00:07, 1489.80it/s]

 83%|████████▎ | 58001/69488 [00:48<00:11, 1006.12it/s]

 84%|████████▍ | 58273/69488 [00:48<00:09, 1200.65it/s]

 84%|████████▍ | 58662/69488 [00:49<00:06, 1576.46it/s]

 85%|████████▍ | 59001/69488 [00:49<00:09, 1083.34it/s]

 85%|████████▌ | 59380/69488 [00:49<00:07, 1409.01it/s]

 86%|████████▌ | 59768/69488 [00:49<00:05, 1772.00it/s]

 86%|████████▋ | 60068/69488 [00:50<00:08, 1173.73it/s]

 87%|████████▋ | 60464/69488 [00:50<00:05, 1529.79it/s]

 88%|████████▊ | 60840/69488 [00:50<00:04, 1872.97it/s]

 88%|████████▊ | 61148/69488 [00:51<00:08, 994.46it/s]

 89%|████████▊ | 61502/69488 [00:51<00:06, 1272.63it/s]

 89%|████████▉ | 61867/69488 [00:51<00:04, 1592.34it/s]

 89%|████████▉ | 62162/69488 [00:52<00:09, 777.64it/s]

 90%|████████▉ | 62495/69488 [00:52<00:06, 1007.59it/s]

 90%|█████████ | 62779/69488 [00:52<00:05, 1216.58it/s]

 91%|█████████ | 63040/69488 [00:53<00:07, 887.50it/s]

 91%|█████████▏| 63408/69488 [00:53<00:05, 1199.41it/s]

 92%|█████████▏| 63862/69488 [00:53<00:03, 1658.85it/s]

 92%|█████████▏| 64172/69488 [00:53<00:04, 1173.46it/s]

 93%|█████████▎| 64586/69488 [00:53<00:03, 1545.12it/s]

 94%|█████████▎| 65001/69488 [00:54<00:03, 1193.47it/s]

 94%|█████████▍| 65399/69488 [00:54<00:02, 1523.17it/s]

 95%|█████████▍| 65828/69488 [00:54<00:01, 1923.16it/s]

 95%|█████████▌| 66151/69488 [00:55<00:03, 938.23it/s]

 96%|█████████▌| 66480/69488 [00:55<00:02, 1165.14it/s]

 96%|█████████▋| 66889/69488 [00:55<00:01, 1519.05it/s]

 97%|█████████▋| 67197/69488 [00:56<00:02, 987.16it/s]

 97%|█████████▋| 67563/69488 [00:56<00:01, 1271.02it/s]

 98%|█████████▊| 67859/69488 [00:56<00:01, 1493.34it/s]

 98%|█████████▊| 68138/69488 [00:57<00:01, 847.68it/s]

 98%|█████████▊| 68345/69488 [00:57<00:01, 946.00it/s]

 99%|█████████▊| 68560/69488 [00:57<00:00, 1094.87it/s]

 99%|█████████▉| 68866/69488 [00:57<00:00, 1388.28it/s]

 99%|█████████▉| 69097/69488 [00:57<00:00, 1085.43it/s]

100%|█████████▉| 69433/69488 [00:57<00:00, 1425.71it/s]

100%|██████████| 69488/69488 [00:57<00:00, 1199.56it/s]

Fitting vectorizer...

Vectorizing...

In [17]:
X_train = data_train
[data_train.shape, y_train.values.ravel().shape]

[(69488, 8000), (69488,)]

In [18]:
data_test = pr.transform(X_test, mode='test')
data_test = pd.DataFrame.sparse.from_spmatrix(data_test, columns=pr.vectorizer.get_feature_names_out())
y_test = pd.DataFrame(y_test)
y_test = y_test[y_test.index.isin(pr.test_idx)]
y_test.index = data_test.index

Removing Nans...
Counting capitalized...
Lowering...
Removing URLs...
Removing Punctuation...
Removing double space...
Removing emojis...
Removing stopwords...

  0%|          | 0/999 [00:00<?, ?it/s]

100%|██████████| 999/999 [00:00<00:00, 236355.47it/s]

Removing numbers...

  0%|          | 0/999 [00:00<?, ?it/s]

100%|██████████| 999/999 [00:00<00:00, 624643.66it/s]

Lemmatizing...

  0%|          | 0/999 [00:00<?, ?it/s]

  0%|          | 1/999 [00:00<10:36,  1.57it/s]

 19%|█▉        | 189/999 [00:00<00:02, 345.17it/s]

 49%|████▉     | 490/999 [00:00<00:00, 896.77it/s]

 83%|████████▎ | 825/999 [00:00<00:00, 1456.54it/s]

100%|██████████| 999/999 [00:00<00:00, 1004.81it/s]

Vectorizing...

In [19]:
X_test = data_test
[X_test.shape, y_test.values.ravel().shape]

[(999, 8000), (999,)]

In [20]:
dump(pr.vectorizer, 'vectorizer.model')

['vectorizer.model']

# Classification

In [21]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(random_state=42, max_iter=1000)
log_reg.fit(X_train, y_train.values.ravel())

dump(log_reg, 'log_reg.model')

['log_reg.model']

In [22]:
clf = load('log_reg.model') 
y_pred  = clf.predict(X_test)

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, target_names = le.inverse_transform(np.unique(y_test))))

              precision    recall  f1-score   support

  Irrelevant       0.90      0.80      0.85       172
    Negative       0.83      0.90      0.86       266
     Neutral       0.87      0.80      0.83       285
    Positive       0.82      0.88      0.85       276

    accuracy                           0.85       999
   macro avg       0.86      0.84      0.85       999
weighted avg       0.85      0.85      0.85       999

In [24]:
from sklearn.tree import DecisionTreeClassifier

## Criterion: entropy or gini
classifier = DecisionTreeClassifier(max_depth=600, criterion='gini', random_state = 42) 
classifier.fit(X_train,y_train)

dump(classifier, 'tree.model')

['tree.model']

In [25]:
clf = load('tree.model') 
y_pred  = clf.predict(X_test)

In [26]:
print(classification_report(y_test, y_pred, target_names = le.inverse_transform(np.unique(y_test))))

              precision    recall  f1-score   support

  Irrelevant       0.93      0.91      0.92       172
    Negative       0.90      0.95      0.92       266
     Neutral       0.93      0.86      0.90       285
    Positive       0.88      0.91      0.89       276

    accuracy                           0.91       999
   macro avg       0.91      0.91      0.91       999
weighted avg       0.91      0.91      0.91       999

In [27]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=600, random_state=42)
clf.fit(X_train, y_train.values.ravel())

dump(clf, 'forest.model')

['forest.model']

In [28]:
clf = load('forest.model') 
y_pred  = clf.predict(X_test)

In [29]:
print(classification_report(y_test, y_pred, target_names = le.inverse_transform(np.unique(y_test))))

              precision    recall  f1-score   support

  Irrelevant       0.99      0.92      0.96       172
    Negative       0.95      0.97      0.96       266
     Neutral       0.96      0.93      0.95       285
    Positive       0.91      0.95      0.93       276

    accuracy                           0.95       999
   macro avg       0.95      0.95      0.95       999
weighted avg       0.95      0.95      0.95       999

# All together

In [30]:
log_reg = load('log_reg.model') 
y_lr  = log_reg.predict(X_test)

tree = load('tree.model') 
y_tree  = tree.predict(X_test)

forest = load('forest.model') 
y_forest  = forest.predict(X_test)

In [31]:
from statistics import mode

y_pred = []

for i in range(len(y_test)):
    
    r = mode([y_lr[i], y_tree[i], y_forest[i]])
    
    y_pred.append(r)

In [32]:
print(classification_report(y_test, y_pred, target_names = le.inverse_transform(np.unique(y_test))))

              precision    recall  f1-score   support

  Irrelevant       0.98      0.94      0.96       172
    Negative       0.96      0.96      0.96       266
     Neutral       0.95      0.94      0.95       285
    Positive       0.92      0.96      0.94       276

    accuracy                           0.95       999
   macro avg       0.95      0.95      0.95       999
weighted avg       0.95      0.95      0.95       999

In [33]:
prueba = data_test[0:1]

x_std = prueba

log_reg = load('log_reg.model') 
y_lr  = log_reg.predict(x_std)

tree = load('tree.model') 
y_tree  = tree.predict(x_std)

forest = load('forest.model') 
y_forest  = forest.predict(x_std)

r = [y_lr[0], y_tree[0], y_forest[0]]

mode(r)

np.int64(0)

In [34]:
y_test[0:1]

   0
0  0

In [35]:
r = load('vectorizer.model')